version: '3.7'
services:
  figma-development:
    build:
      context: .
      dockerfile: Dockerfile
    image: figma-development/app
    container_name: figma-development
    restart: always
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      TZ: Asia/Dhaka
    working_dir: /var/www/frontend

    network_mode: host
   